services:
#Layanan Database 
  database_compro:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: "compro_nim!123"
      MARIADB_DATABASE: dbcompro_nim
      MARIADB_USER: usercompro_nim
      MARIADB_PASSWORD: "12345"
    volumes:
      - db_data_v2:/var/lib/mysql
      - ./database/dbcompro_nim.sql:/docker-entrypoint-initdb.d/dbcompro_nim.sql:ro
    restart: always
  
# Layanan Web Statis
  kontainer-statis:
    image: mohamadfirdaus12/himafor_nim:latest
    container_name: kontainer-statis
    ports:
      - "80:80"
    restart: always
      
  # Layanan Web Dinamis
  kontainer-dinamis:
    image: mohamadfirdaus12/web-dinamis:latest
    container_name: kontainer-dinamis
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: database_compro
      DB_USER: usercompro_nim
      DB_PASSWORD: "12345"
      DB_NAME: dbcompro_nim
    depends_on:
      - database_compro
  
volumes:
  db_data_v2: {}